name: Ping Supabase

on:
  schedule:
    - cron: '0 0 */7 * *'  # Runs every 7 days

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Supabase
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      run: |
        curl -I "$SUPABASE_URL"
