name: Ping Supabase

on:
  schedule:
    - cron: '0 0 */7 * *'  # Runs every 7 days
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Supabase Auth API
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
      run: |
        curl -I "$SUPABASE_URL/auth/v1" -H "apikey: $SUPABASE_API_KEY"
