name: Keep Supabase Alive

on:
  schedule:
    - cron: '0 0 * * 0'  # This means every 7 days at midnight

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send a ping request to Supabase
        run: |
          curl -X GET "https://bggtinchqyqiwdipbxcw.supabase.co"
