name: Ping Supabase Daily

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
    - name: Ping Supabase
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      run: |
        response=$(curl -sS -o /dev/null -w "%{http_code}" "$SUPABASE_URL")
        if [ $response -eq 200 ]; then
          echo "Supabase pinged successfully"
        else
          echo "Failed to ping Supabase. HTTP status code: $response"
          exit 1
        fi
